name: Lint and publish charts

on:
  pull_request:
    paths:
      - charts/**/*
  push:
    paths:
      - .github/workflows/charts.yml
      - charts/**/*
jobs:
  helm-publish:
    if: >-
      (github.event_name == 'push' && github.ref == 'master')
    runs-on: ubuntu-latest
    needs: [helm-lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout old repo
        uses: actions/checkout@v2.0.0
        with:
          ref: gh-pages
          path: old-repo
      - name: Prepare repo folder
        run: |
          mkdir -p repo
          if [ -f "old-repo/index.yaml" ]; then mv old-repo/index.yaml repo; fi
          find old-repo/  -maxdepth 1 -name '*.tgz' -exec mv {} repo \;
      - name: Download Helm
        run: |
          curl -L https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz | tar -xzf - --strip-component=1 linux-amd64/helm
          chmod +x helm
      - name: Package charts
        run: |
          find charts/ -mindepth 1 -maxdepth 1  -type d -exec ./helm dependency build {} \;
          find charts/ -mindepth 1 -maxdepth 1  -type d -exec ./helm package --destination repo {} \;
          ./helm repo index --merge repo/index.yaml repo
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.9.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./repo
        with:
          forceOrphan: true
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Download Helm
        run: |
          curl -L https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz | tar -xzf - --strip-component=1 linux-amd64/helm
          chmod +x helm
      - name: Lint using helm
        run: |
          ./helm lint charts/*
